### ISSUE TITLE
Empty strings could perhaps be handled in a more user friendly way?

### ISSUE THREAD

**Issue by bjartwolf** [nrkno/Quibble#12]
```
  Assert.JsonEqual("", "");   
```

returns

```
An unhandled exception of type 'System.Text.Json.JsonReaderException' occurred in System.Text.Json.dll: 'The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.'
```

which probably is true, it is not valid JSON as I understand it, but in a case where one for example tries to read it in from an external source some helpful validation could say more specifically which argument was not valid JSON in the case of empty string?

**Comment by einarwh** [comment]
https://github.com/nrkno/Quibble/pull/14
