### ISSUE TITLE
Would it be possible for Quibble to work with FSharp.Core 7.x?

### ISSUE THREAD

**Issue by marklam** [nrkno/Quibble#20]
(There's no issue tracker on the fork of @einarwh where the releases seem to come from, so I'm asking here)

The nuget package specifies FSharp.Core < 7.0.0 - would it be possible to remove this restriction, or update to use FSharp.Core 7 onwards? 

Any projects with a package requiring FSharp.Core.7 can't update Quibble from 0.2.51 to 0.3 of this upper limit.

Thanks for your time!

**Comment by einarwh** [comment]
Hi Mark, 

Thanks for raising this issue and sorry for the late reply. I will look into it.

**Comment by marklam** [comment]
No need to apologise!

Tusen takk!

**Comment by einarwh** [comment]
I've published v0.3.1 of Quibble which removes the version constraint for FSharp.Core. Let me know if there are any issues.

**Comment by marklam** [comment]
Seems to build and run fine with the new version. Thanks!
