### ISSUE TITLE
FSharp.Core can require minimum version of 4.7 instead of 4.7.1

### ISSUE THREAD

**Issue by object** [nrkno/Quibble#4]
FSharp.Core guidelines recommend setting lowest possible minimum version for libraries (https://fsharp.github.io/2015/04/18/fsharp-core-notes.html).

The lowest version of FSharp.Core that targets .NET Standard 2.0 is 4.7, so it would be great if Quibble referenced that version.

**Comment by einarwh** [comment]
https://github.com/nrkno/json-quibble/commit/fbece753214b3d81e5df16e15c459d7881ebbcb3
