### ISSUE TITLE
Possibly require .NET Standard 2.0 instead of 2.1

### ISSUE THREAD

**Issue by object** [nrkno/Quibble#5]
I am not quite sure about this one since .NET Standard 2.0 support is only needed for legacy apps and libraries and supporting legacy apps without good reasons sometimes become a burden. But as long as Quibble does not require .NET Standard 2.1 it may lower required .NET Standard version to 2.0.

**Comment by einarwh** [comment]
https://github.com/nrkno/json-quibble/pull/1
